version: '3.3'
services:
  redis_server:
    container_name: redis_server
    restart: always
    image: redis:7.4.0
    ports:
      - "6379:6379"
    volumes:
      - /home/monitoringbbsk/rpi_local_files/console_components/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  consoleenviromonitorrpi:
    container_name: console
    privileged: true
    restart: always
    image: cetniqhub/consoleenviromonitorrpi:v0.93
    network_mode: host
    devices:
      - /dev/ttyUSB0
    volumes:
      - /home/monitoringbbsk/rpi_local_files/console_components/logs:/app/logs
    logging:  
      driver: local
      options:
        max-size: "10m"  
        max-file: "3"
